### ISSUE TITLE
[SVC-2958] Include client request info in external verification request

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#123]
**Motivation**

Verification requests need to have more information about the caller for anti-botting purposes.

**Requirements**

* Provide both `backend::net::ClientInfo` and `backend::net::IpInfo`

<sub>From [SyncLinear.com](https://synclinear.com) | [SVC-2958](https://linear.app/rivet-gg/issue/SVC-2958/include-client-request-info-in-external-verification-request)</sub>

**Comment by MasterPtato** [comment]
@NathanFlurry a mm-lobby-find request can include multiple players, i assume we want to send all of the client and ip info to the external request?

**Comment by NathanFlurry** [comment]
yes
