### ISSUE TITLE
New lobby type - Proxy/Router

### ISSUE THREAD

**Issue by jog1t** [rivet-gg/rivet#147]
## Description

I don't want to create a separate build for a dedicated server - one of the players should be able to host the game and somehow other players should be able to connect to it without any issues. That lobby, a proxy lobby, would proxy the traffic from all the players connected to it, without hosting or running a dedicated server. Having a lobby that proxies the traffic, bypassing restrictions of firewall, NAT and other things would be beneficial for such games and developers behind them. 
This could minimize the costs of maintaining a separate build and costs related to hosting a dedicated lobby.

## Alternatives solutions

Alternative solution to Proxy Lobby is just entering a hosting player's IP in the game interface, but that's only applicable when user has firewall disabled for certain ports, and it is not behind the NAT.

## Prior art

Most of cooperative games does not need dedicated server nor lobby.  Unfortunately, I'm not aware how Steamworks Multiplayer works, but games like Plate Up, Overcooked, Portal 2, Factorio have an option to host the game "locally", so other players can join without knowing hosting player's ip address.

**Comment by NathanFlurry** [comment]
no longer relevant with rivet actors. added CON-173
