### ISSUE TITLE
[SVC-3362] Add `bolt admin` CLI command to promote user to admin

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#152]
**Motivation**

Every new cluster needs to promote a user to admin. At the moment, this is done via an SQL query, which does not purge the cache appropriately.

<sub>From [SyncLinear.com](https://synclinear.com) | [SVC-3362](https://linear.app/rivet-gg/issue/SVC-3362)</sub>

**Comment by AngelOnFira** [comment]
I think this was resolved by #177?

**Comment by NathanFlurry** [comment]
Out of sync with Linear
