### ISSUE TITLE
[SVC-3105] Set up Github Code Spaces

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#161]
**Motivation**

Make it easy to set up a Rivet cluster in one click without installing anything.

**Potential Issues**

* Does Code Spaces have a static public IP or will we have to use something like Ngrok?

<sub>From [SyncLinear.com](https://synclinear.com) | [SVC-3105](https://linear.app/rivet-gg/issue/SVC-3105)</sub>

**Comment by AngelOnFira** [comment]
I'm going to work on this issue :)

Some initial questions I want to figure out:
- The DEVELOPMENT.md mentions needing a Linode/Cloudflare account. I wonder if there's a way to not require this for local development, or specify more why it's needed
- I'm curious how the nix shell should be setup when you start the container. Should it clone the most up-to-date version of Rivet?
- Would it be nice to have more images in DEVELOPMENT.md of the UI?

**Comment by AngelOnFira** [comment]
It would probably also be good for nix stuff to be cached ahead of time if possible. Though I don't know if this will cause a problem for image size.

**Comment by NathanFlurry** [comment]
Out of sync with Linear
