### ISSUE TITLE
Is the architecture diagram is correct?

### ISSUE THREAD

**Issue by fire** [rivet-gg/rivet#1679]
## Environment

- [ ] Rivet Cloud
  - Game ID: [please provide]
- [ ] Rivet self-hosted local
  - Version/commit: [please provide]
- [x] Rivet self-hosted cluster
  - Version/commit: [please provide]

## Description

Is the architecture diagram correct?

## Steps to reproduce

1. Read the https://github.com/rivet-gg/rivet readme
2. Check the diagram.
3. Check the actual architecture

## Workarounds

???

Your comment mentioned there is no redis in the architecture.

## More information

https://news.ycombinator.com/item?id=42472780

**Comment by NathanFlurry** [comment]
hey @fire! we updated the diagram a few weeks ago, it should be up to date. we still use valkey (redis) for simple caching.

we used to use redis for more complicated things like our matchmaking service and route management.

closing, but happy to answer any questions
