### ISSUE TITLE
Project 

### ISSUE THREAD

**Issue by gallabi** [rivet-gg/rivet#1699]
from django.db import models

class سعر_الذهب_الخام(models.Model):
    التاريخ = models.DateField()
    السعر_بالجرام = models.DecimalField(max_digits=10, decimal_places=2)

    def __str__(self):
        return f"{self.السعر_بالجرام} جرام في {self.التاريخ}"

class الذهب_الخام(models.Model):
    رقم_المرجع = models.CharField(max_length=20, unique=True)
    تاريخ_الاستخراج = models.DateField()
    نسبة_العيار = models.DecimalField(max_digits=5, decimal_places=3)
    الكمية_بالجرام = models.IntegerField()
    مصدر_الخام = models.CharField(max_length=100)
    السعر = models.ForeignKey(سعر_الذهب_الخام, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.رقم_المرجع

class التكاليف(models.Model):
    نوع_التكلفة = models.CharField(max_length=50)
    المبلغ = models.DecimalField(max_digits=10, decimal_places=2)
    تاريخ_التكلفة = models.DateField()
    الذهب_الخام = models.ForeignKey(الذهب_الخام, on_delete=models.CASCADE, related_name='التكاليف')

    def __str__(self):
        return f"{self.نوع_التكلفة} - {self.المبلغ} جرام"

**Comment by NathanFlurry** [comment]
what
