### ISSUE TITLE
Add support for other email providers

### ISSUE THREAD

**Issue by Laurence-Walpole** [rivet-gg/rivet#173]
## Description

While trying to setup my development environment, I came across an issue when creating a SendGrid account. This appears to be based off of my phone number or email domain provider.

Limiting Rivet to just being able to use SendGrid seems like a bottleneck that can be easily avoided by allowing other providers to be configured during the Bolt setup process.

Examples of these could be [Postmark](https://postmarkapp.com/pricing), [Mailchimp](https://mailchimp.com/features/transactional-email/) or [MailGun](https://www.mailgun.com/)

## Alternatives solutions

Provide a choice in the setup process for the dev environment to disable transactional emails.

## Prior art

N/A

**Comment by NathanFlurry** [comment]
we overhauled our self-hosted setup to not require email for login, this should no longer be an issue.
