### ISSUE TITLE
[RVT-2958] Include client request info in external verification request

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#252]
**Motivation**

Verification requests need to have more information about the caller for anti-botting purposes.

**Requirements**

* Provide both `backend::net::ClientInfo` and `backend::net::IpInfo`

<sub>From [SyncLinear.com](https://synclinear.com) | [RVT-2958](https://linear.app/rivet-gg/issue/RVT-2958)</sub>

**Comment by MasterPtato** [comment]
Already done
