### ISSUE TITLE
[RVT-179] Migrate to official Nomad OpenAPI client

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#254]
**Motivation**

We're using an old OpenAPI client ([https://github.com/rivet-gg/Nomad.OAS](https://github.com/rivet-gg/Nomad.OAS)), we should switch to using the official client so we get future updates. There is no change in functionality.

**Implementation**

See [https://github.com/hashicorp/nomad-openapi](https://github.com/hashicorp/nomad-openapi)

<sub>From [SyncLinear.com](https://synclinear.com) | [RVT-179](https://linear.app/rivet-gg/issue/RVT-179)</sub>

**Comment by ravikiran232** [comment]
@NathanFlurry I'm taking the issue.

**Comment by NathanFlurry** [comment]
Out of sync with Linear
