### ISSUE TITLE
[RVT-2367] Remove salt-key for deleted servers

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#267]
* When we delete a server, `salt apply` fails because the server is no longer reachable
* Add a `null_resource` with a shell script in `pools` that calls `salt-key -D` on any servers not present in Terraform
  * Use `triggers` to automatically calls this when the servers change

<sub>From [SyncLinear.com](https://synclinear.com) | [RVT-2367](https://linear.app/rivet-gg/issue/RVT-2367)</sub>

**Comment by MasterPtato** [comment]
Salt doesn't exist anymore
