### ISSUE TITLE
Allow disabling max players per IP

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#327]
## Description

If making API requests from the backend, the IP limitations are not helpful. The max players per IP needs to be disabled in order to allow backend-facing API calls.

## Alternatives solutions

Require everyone to use server-verified requests and make requests from clients. This is not as easy as making requests directly from the backend.

<sub>[RVT-3537](https://linear.app/rivet-gg/issue/RVT-3537)</sub>

**Comment by MasterPtato** [comment]
Is this a duplicate? [RVT-3536](https://linear.app/rivet-gg/issue/RVT-3536)

**Comment by NathanFlurry** [comment]
@max sync linear was causing issues. i unlinked it now, removing the dupe.
