### ISSUE TITLE
Improve public IP requirement

### ISSUE THREAD

**Issue by AngelOnFira** [rivet-gg/rivet#511]
Currently, bringing up Rivet will encode your public IP into the namespace config. This prevents certain containers from being brought up, since they'll try to be reached through a public IP, and fail.

A solution to allow the cluster to be brought up is to change the `public_ip` to `127.0.0.1` manually. This also doesn't let the full cluster work. Documentation for this could help, or adding a command to bolt to specify that it should set up on localhost.

However, I think there are still issues when it comes to running just on localhost, as you won't be able to use the hub after it starts. @nathan can you elaborate on the issues of using localhost?

**Comment by NathanFlurry** [comment]
Dev tunnels fixes this.
