### ISSUE TITLE
Bolt build in nix-shell fails on Darwin (macOS)

### ISSUE THREAD

**Issue by MaxCWhitehead** [rivet-gg/rivet#588]
## Environment

-   [ ] Rivet self-hosted local
    -   Version/commit: [main branch [dc6cd79d254b76d326e3a09215e6853ee40df12d](https://github.com/rivet-gg/rivet/commit/dc6cd79d254b76d326e3a09215e6853ee40df12d)]
    
    MacOS Sonoma 14.2.1 - running shell-nix

## Description

Running nix-shell fails to build (link) Bolt.

```
error: linking with `/nix/store/b0d5xkncz7jn72kkgzsaizpk9170mybf-clang-wrapper-11.1.0/bin/cc` failed: exit status: 1

... (truncated massive linker command)

>   = note: ld: framework not found SystemConfiguration
       >           clang-11: error: linker command failed with exit code 1 (use -v to see invocation)
       >
       >
       > error: could not compile `bolt` (bin "bolt") due to 1 previous error
       For full logs, run 'nix log /nix/store/ry3mp50y8rz3466qgchkkn54k73hiih3-bolt.drv'.
```

## Steps to reproduce

1. Clone rivet on macOS (see version above)
2. `nix-shell` in project root
3. Wait for build failure

**Comment by NathanFlurry** [comment]
Hey! At the moment, you can work around this by running Rivet on macOS using the [dev containers](https://github.com/rivet-gg/rivet/blob/main/docs/getting_started/DEVELOPMENT.md#dev-container).

We're working on improving & simplifying self-hosting support in the next couple months:
https://github.com/rivet-gg/rivet/issues/591
https://github.com/rivet-gg/rivet/issues/593
https://github.com/rivet-gg/rivet/issues/592
