### ISSUE TITLE
ClickHouse password should URL encode special character

### ISSUE THREAD

**Issue by NathanFlurry** [rivet-gg/rivet#720]
We generate 1 special character in our ClickHouse password because of the requirement for ClickHouse cloud.

Some characters (e.g. "#") need to be encoded in the password, but instead get injected directly and are interpreted as an anchor, causing the driver to use the wrong URL.

**Comment by AngelOnFira** [comment]
Can we instead just use a subset of special characters that don't have problems when generating passwords?
