### ISSUE TITLE
[SVC-2692] Add readable region name to env of game lobbies

### ISSUE THREAD

**Issue by MasterPtato** [rivet-gg/rivet#89]
Along with the region ID and region identifier, include the human-readable display name of the lobby's region (as given in the /list endpoint)

<sub>From [SyncLinear.com](https://synclinear.com) | [SVC-2692](https://linear.app/rivet-gg/issue/SVC-2692/add-readable-region-name-to-env-of-game-lobbies)</sub>

**Comment by NathanFlurry** [comment]
Out of sync with Linear
